version: '3.6'
services:
  postgres:
    container_name: ddev-${DDEV_SITENAME}-postgres
    image: mdillon/postgis:11
    ports:
      - 32785:5432
    environment:
      - POSTGRES_PASSWORD=db
      - POSTGRES_USER=db
      - POSTGRES_DB=db
    volumes:
      - type: "volume"
        source: postgres
        target: "/var/lib/postgresql/data"
        volume:
          nocopy: true
      - type: "bind"
        source: "."
        target: "/mnt/ddev_config"
      - ddev-global-cache:/mnt/ddev-global-cache
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
  web:
    links:
      - postgres:postgres

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@career.ddev.site
      PGADMIN_DEFAULT_USERNAME: db
      PGADMIN_DEFAULT_PASSWORD: db
      PGADMIN_LISTEN_PORT: 8081
    ports: 
      - "8080:8081"
    volumes: 
      - pgadmin-data:/var/lib/pgadmin
    links: 
      - "postgres:pgsql-server"

volumes:
  postgres:
  pgadmin-data: