paragraph_blocks.settings:
  type: config_object
  label: 'Paragraph blocks settings'
  mapping:
    max_cardinality:
      type: integer
      label: 'Max Cardinality to display in the UI for placement'
