<?php

/**
 * @file
 */


/**
 * Implements hook_install().
 *
 * Fix menu_link_content bundle field link_override.
 */
function workbc_tr_build_update_8506() {
  $definition_update_manager = \Drupal::entityDefinitionUpdateManager();
  $field_definition = $definition_update_manager->getFieldStorageDefinition('field_para_simple_title', 'paragraph');
  $definition_update_manager->updateFieldStorageDefinition($field_definition);
}