<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 *
 */
function workbc_tr_build_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'simplenews_subscriptions_block_simple-new-teachers') {
    $form['mail']['#markup'] = '<div class="subscribe-wrapper"><p>' . t("Enter your email address below to receive an email when new lesson plans and resources become available.") . '<p></div>';
    $form['actions']['subscribe']['#value'] = t('Sign up');
  }
}
