<?php

/**
 * @file
 * Install, update and uninstall functions for the module_filter module.
 */

/**
 * Implements hook_install().
 */
function module_filter_install() {
  $state = \Drupal::state();
  $state->set('module_filter.recent', ['module_filter' => \Drupal::time()->getRequestTime()]);
}

/**
 * Implements hook_uninstall().
 */
function module_filter_uninstall() {
  $state = \Drupal::state();
  $state->delete('module_filter.recent');
}
