name: Tag-Prod

on:
  push:
    tags: 
      - "v[0-9]+.[0-9]+-prod*"

env:
  IMAGE_ID: ${{ secrets.AWS_ECR_URI }}
  
permissions:
  id-token: write
  contents: read
jobs:
  main:
    name: main
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_TO_USE_TOOLS }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create Docker Tag
        run: |
          docker pull ${{ env.IMAGE_ID }}:latest-test
          docker tag ${{ env.IMAGE_ID }}:latest-test ${{ env.IMAGE_ID }}:${GITHUB_REF#refs/tags/}
          docker push ${{ env.IMAGE_ID }}:${GITHUB_REF#refs/tags/}
